### ISSUE TITLE
[finances] Investor Flow of Funds

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#54]
Data on flows into and out of funds in the US from http://www.ici.org/research/stats

**Comment by rgrp** [comment]
All packaged up https://github.com/datasets/investor-flow-of-funds-us but needs a maintainer!

**Comment by EnricGTorrents** [comment]
I can take care of it, data needs to be collected every first day of the month?

**Comment by rgrp** [comment]
@EnricGTorrents that's right - you need to run the script every month or less (that way we get full weekly data). Do you want to try running the script now and submitting a pull request. I can then give you full write access to the repo: https://github.com/datasets/investor-flow-of-funds-us

**Comment by EnricGTorrents** [comment]
Got these errors with dataconverters and messytables when running the script on Python 3.4.3:

```
Traceback (most recent call last):
  File "C:\Users\Research Computer\Desktop\Open Knowledge Foundation\investor-flow-of-funds-us\scripts\process.py", line 6, in <module>
    from dataconverters import xls
  File "C:\Python34\lib\site-packages\dataconverters\__init__.py", line 3, in <module>
    import dataconverters.commas as dcsv
  File "C:\Python34\lib\site-packages\dataconverters\commas.py", line 5, in <module>
    from messytables import (
  File "C:\Python34\lib\site-packages\messytables\__init__.py", line 3, in <module>
    from messytables.headers import headers_guess, headers_processor, headers_make_unique
  File "C:\Python34\lib\site-packages\messytables\headers.py", line 18
    return max(counts.items(), key=lambda (k, v): v)[0]
                                          ^
SyntaxError: invalid syntax
```

Right now I am on Windows 8, I will try again later on another platform and / or Python version. Not sure what is causing the problem, any suggestions on how to proceed?

**Comment by EnricGTorrents** [comment]
Ok, managed to run the script in Linux (Debian Wheezy) with Python 2.7.3. Seems that the problem on Win8 / Python 3.4 had to do with lxml. On a Debian cleanslate installation got to get it first (apt-get install libxml2-dev libxslt1-dev python-dev / apt-get install python-lxml). The package unicodecsv is also required but not included in the requirements.txt. I will now send a pull request with the data.

**Comment by rgrp** [comment]
@EnricGTorrents how are you doing here? Would be great to have you as maintainer here.

/cc @Yannael are you happy to follow up to support @EnricGTorrents here if he has any problems?

**Comment by Yannael** [comment]
@rgrp sure
@EnricGTorrents Let me know if I can help
